# Generated by Django 4.1.1 on 2023-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_of_kin_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
